// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolcaEtiquetadoManual.Data.Context;

#nullable disable

namespace MolcaEtiquetadoManual.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502230657_Creardb")]
    partial class Creardb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MolcaEtiquetadoManual.Core.Models.EtiquetaGenerada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit");

                    b.Property<string>("DOCO")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOCO");

                    b.Property<string>("EDDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EDDT");

                    b.Property<int>("EDLN")
                        .HasColumnType("int")
                        .HasColumnName("EDLN");

                    b.Property<string>("EDTN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EDTN");

                    b.Property<string>("EDUS")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("EDUS");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("EXPR")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPR");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("LITM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LITM");

                    b.Property<string>("LOTN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOTN");

                    b.Property<int>("LineaId")
                        .HasColumnType("int")
                        .HasColumnName("LINEID");

                    b.Property<int>("SEC")
                        .HasColumnType("int")
                        .HasColumnName("SEC");

                    b.Property<string>("SHFT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SHFT");

                    b.Property<int>("SOQS")
                        .HasColumnType("int")
                        .HasColumnName("SOQS");

                    b.Property<string>("TDAY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TDAY");

                    b.Property<string>("UOM1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UOM");

                    b.Property<string>("URDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URDT");

                    b.Property<string>("URRF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URRF");

                    b.HasKey("Id");

                    b.ToTable("SALIDA", (string)null);
                });

            modelBuilder.Entity("MolcaEtiquetadoManual.Core.Models.LineaProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LineasProduccion", (string)null);
                });

            modelBuilder.Entity("MolcaEtiquetadoManual.Core.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("IdLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogico"), 1L, 1);

                    b.Property<int>("CantidadPorPallet")
                        .HasColumnType("int")
                        .HasColumnName("MULT");

                    b.Property<string>("DUN14")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CITM");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DSC1");

                    b.Property<int>("DiasCaducidad")
                        .HasColumnType("int")
                        .HasColumnName("SLD");

                    b.Property<DateTime>("FechaProduccionFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("DRQJ");

                    b.Property<DateTime>("FechaProduccionInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("STRT");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ITM");

                    b.Property<string>("NumeroArticulo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("LITM");

                    b.Property<string>("ProgramaProduccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOCO");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UOM");

                    b.HasKey("IdLogico");

                    b.ToTable("ENTRADA", (string)null);
                });

            modelBuilder.Entity("MolcaEtiquetadoManual.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
